#!/bin/bash
# use . i0 to use the main thread to run this shell. 
# And this is also the reason why no exit 0 in the end.

# cunstom variables
export Title='192.168.108.101'
export WD='/home/kali/1120914-OSCP-#2Exam'
export LIp='192.168.49.108'
export RIp='192.168.108.101'

source /home/kali/Tools/i_base
